### ISSUE TITLE
Where do I add my api key to test this?

### ISSUE THREAD

**Issue by plusnarrative-phillip** [victordibia/autogen-ui#2]
Apologies the documentation did not make this clear, I am unable to test this but would love to try it out

**Comment by victordibia** [comment]
Good catch.
I updated the readme. 

There are two options:
- manuallly set your openai_api_key env variable 
- use the autogent env variable.



```bash
export OPENAI_API_KEY=<your key>
```


Also See this article for how Autogen supports multiple [llm providers](https://microsoft.github.io/autogen/docs/FAQ/#set-your-api-endpoints)

**Comment by plusnarrative-phillip** [comment]
thank you will give it a go
