### ISSUE TITLE
A few issues (missing dependencies, connection error, python version)

### ISSUE THREAD

**Issue by SimonB97** [victordibia/autogen-ui#4]
Hello,

thanks for this template! I followed the instructions carefully, but unfortunately i'm having a few issues:

1. It seems the dependencies require Python >=3.9. I had 3.8 installed but i received this error message:
`ERROR: Package 'autogenui' requires a different Python: 3.8.0 not in '>=3.9'`

2. After switching to 3.9 and trying to launch with `autogenui` i see that `typer` seems to be missing from the dependencies:
`ModuleNotFoundError: No module named 'typer'`

3. After installing typer, i notice that autogen itself is missing too

4. After installing autogen using `pip install autogen`, i can launch with `autogenui`, but when trying to send a message i see
  - in the Brower/app: `Connection error. Ensure server is up and running.`
  - console: `INFO:     127.0.0.1:51780 - "OPTIONS /api/generate HTTP/1.1" 400 Bad Request`

Edit:
| Header | Header |
|--------|--------|
| **OS** | Win 11 |
| **Python** | 3.9.0 |
| **Browser** | MS Edge Dev |

**Comment by plusnarrative-phillip** [comment]
you likely need to create a venv or remove other pythons files and reinstall only the one that is needed, this is the prcie you pay playing with python

**Comment by SimonB97** [comment]
yeah, that's the impression i'm getting too.. though, i've created a new conda env and installed the dependencies into that. 
do you have any guesses where i should start looking for conflicts? 

Thanks!

**Comment by winklerj** [comment]
Check the network requests in your browser. You will get a CORS error if you use 127.0.0.1:8081. You need to use localhost:8081. Also make sure you have your OpenAI key specified as an environment variable.

**Comment by SimonB97** [comment]
Thank you for your help! Although, i found the issue myself, got trolled majorly here...

the issue was that i installed `autogen` instead of `pyautogen`.
