### ISSUE TITLE
Question: setting this up?

### ISSUE THREAD

**Issue by AbubakrChan** [victordibia/autogen-ui#5]
i have successfully cloned this repo but next I am unaware how to make it run.
i could not gather enough information from the readme.md file so could you please give me a hint on how I can make this web ui run with autogen?

thanks

**Comment by plusnarrative-phillip** [comment]
i think he uses a mac or something an does it via the terminal instead of the normal .env way

**Comment by plusnarrative-phillip** [comment]
if you manage to get this working please make a youtube video
