### ISSUE TITLE
Connection error: Ensure server is up and running

### ISSUE THREAD

**Issue by AbubakrChan** [victordibia/autogen-ui#7]
![image](https://github.com/victordibia/autogen-ui/assets/89600478/06d742a3-98e1-4543-9681-e032e5b25e8f)

I am running this on replit and receiving the above error.

Could you please help me on this?

Thanks

**Comment by AbubakrChan** [comment]
![image](https://github.com/victordibia/autogen-ui/assets/89600478/1b41fb4d-ab60-4ce5-aa2d-b726b8e973f9)


This is what I am receiving.

@victordibia  Could you please have a look at this. I will be very thankful to you.

**Comment by victordibia** [comment]
Hi,

I have pushed an update which should solve this. 
Essentially, the UI expects the server to be at url `localhost:8081`. 
Now when you install by default, it should look for the server on the same url. 

```bash 
pip install autogenui
```

to run ui 

```bash
autogenui
```
